services:
  - type: web
    name: justincase-backend
    env: node
    buildCommand: yarn install && yarn workspace justincase-backend build
    startCommand: node packages/backend/dist/main.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
