services:
  - type: web
    name: justincase-backend
    env: node
    rootDir: packages/backend
    buildCommand: yarn --immutable && yarn build
    startCommand: node dist/main.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
