name: Build, lint, and publish

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_lint:
    permissions:
      contents: read
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24
          cache: yarn

      - name: Install packages
        run: |
          yarn --immutable

      - name: Lint and build
        run: |
          yarn lint
          yarn build
          yarn test

  publish_docker_frontend_image:
    name: Publish Docker frontend image
    needs: build_lint
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: docker-meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9
        with:
          images: ghcr.io/${{ github.repository }}-frontend
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha

      - name: Build and push Docker frontend image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          file: frontend.Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}

  deploy_frontend:
    name: Deploy latest frontend image
    runs-on: ubuntu-latest
    needs: publish_docker_frontend_image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      deployments: write
    steps:
      - name: Deploy
        uses: ffflorian/actions/coolify-deploy@9c7842ec0251a5890f0ca9ef22deed8dbc4ea9fa
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          environment: frontend-production
          domain: ${{ secrets.COOLIFY_DOMAIN }}
          token: ${{ secrets.COOLIFY_TOKEN }}
          uuid: ${{ secrets.COOLIFY_UUID_FRONTEND }}

  publish_docker_backend_image:
    name: Publish Docker backend image
    needs: build_lint
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: docker-meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9
        with:
          images: ghcr.io/${{ github.repository }}-backend
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha

      - name: Build and push Docker backend image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          file: backend.Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}

  deploy_backend:
    name: Deploy latest backend image
    runs-on: ubuntu-latest
    needs: publish_docker_backend_image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      deployments: write
    steps:
      - name: Deploy
        uses: ffflorian/actions/coolify-deploy@9c7842ec0251a5890f0ca9ef22deed8dbc4ea9fa
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          environment: backend-production
          domain: ${{ secrets.COOLIFY_DOMAIN }}
          token: ${{ secrets.COOLIFY_TOKEN }}
          uuid: ${{ secrets.COOLIFY_UUID_BACKEND }}
