name: Build, lint, and publish

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_lint:
    permissions:
      contents: read
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24
          cache: yarn

      - name: Install packages
        run: |
          yarn --immutable

      - name: Lint and build
        run: |
          yarn lint
          yarn build
          yarn test

  publish_docker_frontend_image:
    name: Publish Docker frontend image
    needs: build_lint
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: docker-meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          images: ghcr.io/${{ github.repository }}-frontend
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha

      - name: Build and push Docker frontend image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          file: frontend.Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}

  deploy_frontend:
    name: Deploy latest frontend image
    runs-on: ubuntu-latest
    needs: publish_docker_frontend_image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions: {}
    steps:
      - name: Deploy
        uses: ffflorian/actions/coolify-deploy@395dd69a8fe27cbaaf9ee09ebfaeefaf92dfdda5
        with:
          domain: ${{ secrets.COOLIFY_DOMAIN }}
          token: ${{ secrets.COOLIFY_TOKEN }}
          uuid: ${{ secrets.COOLIFY_UUID_FRONTEND }}

  publish_docker_backend_image:
    name: Publish Docker backend image
    needs: build_lint
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: docker-meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          images: ghcr.io/${{ github.repository }}-backend
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha

      - name: Build and push Docker backend image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          file: backend.Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}

  deploy_backend:
    name: Deploy latest backend image
    runs-on: ubuntu-latest
    needs: publish_docker_backend_image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions: {}
    steps:
      - name: Deploy
        uses: ffflorian/actions/coolify-deploy@395dd69a8fe27cbaaf9ee09ebfaeefaf92dfdda5
        with:
          domain: ${{ secrets.COOLIFY_DOMAIN }}
          token: ${{ secrets.COOLIFY_TOKEN }}
          uuid: ${{ secrets.COOLIFY_UUID_BACKEND }}
