name: Delete old package versions

permissions: {}

on:
  schedule:
    - cron: '0 4 * * 1' # Runs every Monday at 4:00 AM
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  delete_old_frontend_packages:
    name: Delete old frontend package versions
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55
        with:
          package-name: 'justincase-frontend'
          package-type: 'container'
          min-versions-to-keep: 2

  delete_old_backend_packages:
    name: Delete old backend package versions
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55
        with:
          package-name: 'justincase-backend'
          package-type: 'container'
          min-versions-to-keep: 2
