name: Build

on: [push]

permissions:
  contents: write

jobs:
  vercel_deploy:
    name: Create vercel deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set git author
        env:
          GIT_AUTHOR_NAME: Florian Imdahl
          GIT_AUTHOR_EMAIL: ffflorian@users.noreply.github.com
          GIT_AUTHOR_EMAIL_ALTERNATIVE_1: git@ffflorian.de
          GIT_AUTHOR_EMAIL_ALTERNATIVE_2: dependabot[bot]@users.noreply.github.com
        run: |
          export GIT_COMMITTER_NAME="${GIT_AUTHOR_NAME}"
          export GIT_COMMITTER_EMAIL="${GIT_AUTHOR_EMAIL}"
          export LAST_GIT_AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')

          git config --global "user.email" "${GIT_AUTHOR_EMAIL}"
          git config --global "user.name" "${GIT_AUTHOR_NAME}"

          if [ "${LAST_GIT_AUTHOR_EMAIL}" != "${GIT_AUTHOR_EMAIL}" ] && [ "${LAST_GIT_AUTHOR_EMAIL}" != "${GIT_AUTHOR_EMAIL_ALTERNATIVE_1}" ] && [[ "${LAST_GIT_AUTHOR_EMAIL}" != *"${GIT_AUTHOR_EMAIL_ALTERNATIVE_2}"* ]]; then
            git commit --allow-empty -m "chore: trigger vercel deployment [ci skip]"
            git push
          fi
